"""add critic scores and feedback to posts

Revision ID: b6e250b90c7b
Revises: e60fdf0030d4
Create Date: 2026-05-25 04:29:56.298246

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e250b90c7b'
down_revision: Union[str, None] = 'e60fdf0030d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critic_scores_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('critic_feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('critic_feedback')
        batch_op.drop_column('critic_scores_json')

    # ### end Alembic commands ###
