"""add fact_check_json to posts

Revision ID: 0773bbd0a8ba
Revises: dbb9c66e5381
Create Date: 2026-05-25 19:38:49.553890

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0773bbd0a8ba'
down_revision: Union[str, None] = 'dbb9c66e5381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('few_shot_slugs_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fact_check_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('fact_check_json')
        batch_op.drop_column('few_shot_slugs_json')

    # ### end Alembic commands ###
