"""add few_shot_slugs_json to posts

Revision ID: dbb9c66e5381
Revises: f1cfc05de8f7
Create Date: 2026-05-25 17:58:59.862246

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb9c66e5381'
down_revision: Union[str, None] = 'f1cfc05de8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('few_shot_slugs_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('few_shot_slugs_json')

    # ### end Alembic commands ###
