"""add few_shot_examples

Revision ID: f1cfc05de8f7
Revises: b6e250b90c7b
Create Date: 2026-05-25 04:40:53.021780

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cfc05de8f7'
down_revision: Union[str, None] = 'b6e250b90c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('few_shot_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('rubric', sa.String(length=64), nullable=False, comment='any | 🚀 Запуск/Релиз | 🔻 Скандал | 📊 Цифра дня | ...'),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False, comment='Ретроактивная экспертная оценка [1-10]'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('few_shot_examples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_few_shot_examples_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_few_shot_examples_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_few_shot_examples_rubric'), ['rubric'], unique=False)
        batch_op.create_index(batch_op.f('ix_few_shot_examples_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('few_shot_examples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_few_shot_examples_slug'))
        batch_op.drop_index(batch_op.f('ix_few_shot_examples_rubric'))
        batch_op.drop_index(batch_op.f('ix_few_shot_examples_language'))
        batch_op.drop_index(batch_op.f('ix_few_shot_examples_is_active'))

    op.drop_table('few_shot_examples')
    # ### end Alembic commands ###
